name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  auto_route: ^4.0.1
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  google_sign_in:
  # sizer: ^2.0.15
  responsive_sizer: ^3.0.5+1
  device_preview: ^1.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  flutterfire_ui:
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.6
  crop_your_image:
  image: ^3.1.3
  font_awesome_flutter: ^10.1.0
  uuid:
  cloud_functions: ^3.2.16
  firebase_analytics: ^9.1.9
  firebase_app_check: ^0.0.6+13
  firebase_messaging: ^11.4.1
  firebase_performance: ^0.8.0+13
  # flutter_signin_button: ^2.0.0
  stripe_sdk: ^5.0.0-nullsafety.1
  flutter_dotenv: ^5.0.2
  flutter_multi_formatter: ^2.5.7
  file_picker: ^4.6.0
  http: ^0.13.4
  horizontal_data_table: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  auto_route_generator: ^4.0.0
  json_serializable: ^6.1.5
  freezed: ^2.0.3+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - .env

flutter_gen:
  integrations:
    flutter_svg: true
